name: Build libfreenect2

on:
  push:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt get install -y cmake pkg-config libusb-1.0-0-dev libturbojpeg0-dev libglfw3-dev
        git clone https://github.com/OpenKinect/libfreenect2.git
    - name: Configure
      run: cmake . -B build
      working-directory: libfreenect2
    - name: Build
      run: make -j$(nproc) && make install
      working-directory: libfreenect2/build
