name: Build libfreenect2

on:
  push:

jobs:
  build-linux:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact: linux
    runs-on: ${{matrix.os}}

    steps:
    - name: Install dependencies linux
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake pkg-config libusb-1.0-0-dev libturbojpeg0-dev libglfw3-dev
        git clone https://github.com/OpenKinect/libfreenect2.git
      if: ${{matrix.os == 'ubuntu-latest'}}
    - name: Configure
      run: cmake . -DBUILD_SHARED_LIBS=OFF -Bbuild -DCMAKE_INSTALL_PREFIX=$(pwd)/install
      working-directory: libfreenect2
    - name: Build
      run: cmake --build build
      working-directory: libfreenect2
    - name: Install
      run: cmake --install install
      working-directory: libfreenect2
    - name: Upload library
      uses: actions/upload-artifact@v4
      with:
        name: libfreenect2-${{matrix.artifact}}
        path: libfreenect2/install
          
